### PR TITLE
Happy path

### PR DESCRIPTION
**Pull request by deetz99**
Happy path complete minus some error handling and edge cases

Still need to write tests

Sorry for the huge pr

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-64-cp9t3w4e.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-64-cp9t3w4e.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-64-cp9t3w4e.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
