### PR TITLE
Update help.md

### PR DESCRIPTION
**Pull request by magszymanski**

### CODE REVIEW

**Comment by trishreimer** [comment]
Could we push this into test please?

**Comment by trishreimer** [comment]
What's the most efficient? We can test with the temporary url and if changes are needed, we can update the existing PR.
If we push this PR to test and changes are needed, we create a new PR.
I'm open to whatever is the best approach for text changes.

**Comment by deetz99** [comment]
The temporary url is by far more efficient. It will generate the project in the Dev environment, which for text updates is enough to see the changes. Then if there are any edits to the PR required, you can simply push more changes and generate the temporary url again. Pushing this into the Test environment would require redeploying the Test environment and a new PR each edit.

To generate the temporary url, you can comment /gcbrun, and in a few minutes the link will be created.

**Pull request merged**
