### PR TITLE
updated that warning text to display BC Registries and Digital Services

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
changes:

replace existing warning from SBC connect to BC Registries and Digital Services

### CODE REVIEW

**Comment by EPortman** [comment]
The unit tests are still falling.

**Comment by hanlunBCRegistries** [comment]
> The unit tests are still falling.

yes unit tests using SBC Connect as header to check that why it is falling I think

**Comment by EPortman** [comment]
image


Im sure if you changed 
`const linkTexts = ['Service BC Connect']`
TO
`const linkTexts = ['BC Registries and Digital Services']`

They would pass.

**Comment by EPortman** [comment]
I actrually just tried it and it worked:

image

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-302-j8a4lxml.web.app

**Review by EPortman — APPROVED** [review]
lgtm

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-302-j8a4lxml.web.app

**Pull request merged**
