### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by deetz99**
- add basic error handling & alert to failed/incomplete payment
- prefill account name on create account form
- check if lastArDate === currentYear when loading initial business details, error out or try and use founding date for nextArYear
- prefill ar form if directed to that page and a filing already exists in the store (payment not complete)
- add i18n messages for for input errors
- add i18n to datepicker
- fix datepicker onClickOutside closing datepicker when using month/year selection

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-71-7oygb7ss.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-71-7oygb7ss.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
