### PR TITLE
Mags-text-updates-july18

### PR DESCRIPTION
**Pull request by magszymanski**
Updates to the confirmation page to include a survey link and to AR filing text for references to the BCA and tool tips.

### CODE REVIEW

**Comment by deetz99** [comment]
Great, just so you know, the locales directory only accepts plain text. HTML can only be used inside the markdown (content/) files. I will need to make a small change to support the compliance warning link. 

If you could please add the French translations, then we will merge this into the Dev environment. Then I will fix the compliance warning link with a follow up PR.

**Comment by magszymanski** [comment]
@deetz99 thanks! I updated them - please note that line 262 of the French file also needs a link for the BCA Section 182. Since there is no French version of the B.C. Business Corporations Act, I've kept that title in English. 

@trishreimer, @janisrogers 
I've ran the English text through Google Translate and AI chatbots (w/ the prompt to keep it Canadian French, plain language, grade 6 reading level, etc). Louise is retired and Gen is away until the 22 - who can validate these translations?

**Line 238**
 To update your office addresses and directors, visit Corporate Online. Allow up to one business day for changes to take effect before returning here to file your annual report.
 
Pour mettre à jour les adresses de vos bureaux et vos administrateurs, visitez Corporate Online. Attendez jusqu'à un jour ouvrable pour que les changements prennent effet avant de revenir ici pour déposer votre rapport annuel.

**Line 243**
 AGM information is used to calculate dates for AGM extensions and location changes. It also helps ensure your business stays compliant and in good standing.
 
Les informations sur les AGA sont utilisées pour calculer les dates des prolongations et les changements de lieu des AGA. Cela aide aussi à s'assurer que votre entreprise reste conforme et en règle.

**Line 262**
 Generally, companies hold AGMs every year. Review the [Business Corporations Act (Section 182)](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) to make sure you meet the legislative requirements.

En général, les entreprises tiennent des AGA chaque année. Consultez la [Business Corporations Act (Section 182)](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) pour vous assurer de respecter les exigences législatives.

**Review by deetz99 — APPROVED** [review]
Approving and merging, the dev deployment for this may be broken but I will add the fixes asap.

**Pull request merged**
