### PR TITLE
ui-Rename

### PR DESCRIPTION
**Pull request by deetz99**
- rename some types
- add comment to useSbcNav
- rename sbcNav and routeWithoutLocale composable with 'use' prefix

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-250-pwsgm3d2.web.app

**Comment by deetz99** [comment]
> /gcbrun

@pwei1018 The temp url config needs to be updated. The NUXT_BAR_API_URL is set incorrectly, it's pointing to the NUXT_BASE_URL currently

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-250-pwsgm3d2.web.app

**Comment by pwei1018** [comment]
> > /gcbrun
> 
> @pwei1018 The temp url config needs to be updated. The NUXT_BAR_API_URL is set incorrectly, it's pointing to the NUXT_BASE_URL currently

Anyone has permission can go here to update the configuration. https://console.cloud.google.com/cloud-build/triggers;region=northamerica-northeast1/edit/1aa7887a-119f-4e96-996d-36016cc439b4?project=yfthig-dev

Or let me know what value do you update with it.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-250-pwsgm3d2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-250-pwsgm3d2.web.app

**Comment by deetz99** [comment]
@pwei1018 
Hey thanks, it's saying I don't have access though. 

The NUXT_BAR_API_URL is being set to the temporary url.
Screenshot 2024-06-27 at 4 27 39 PM

But it should be set to the dev api, in this case "https://business-ar-api-dev-dy4loprnwa-nn.a.run.app"

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-250-pwsgm3d2.web.app

**Comment by pwei1018** [comment]
> @pwei1018 Hey thanks, it's saying I don't have access though.
> 
> The NUXT_BAR_API_URL is being set to the temporary url. Screenshot 2024-06-27 at 4 27 39 PM
> 
> But it should be set to the dev api, in this case "https://business-ar-api-dev-dy4loprnwa-nn.a.run.app"

I should fixed it. Can you verify it?

**Comment by deetz99** [comment]
Yes that seems to work now, thank you!

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
