### PR TITLE
feat: watch for route changes to dynamically load help docs based on …

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
Changes:
fix watch for route changes

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-299-msfhvwpc.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-299-msfhvwpc.web.app

**Review by EPortman — APPROVED** [review]
Working for me

**Pull request merged**
