### PR TITLE
304-update French based on feedbacks and fixed language switch issue

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
Description:
This PR includes updates to the French content related to the Annual Report process. Changes include adjustments to the wording, formatting, and some links.

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-3x0vqkpx.web.app

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries - are you working on this?

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson Mags has a revised version of English text, I was talking to Sophie about it to see whether we have to update the French text accordingly. She thinks it is better to check with Mags and make sure it is final version so she could translate it.

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - can you please check on the status of this? THx

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-z46mwfbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-z46mwfbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-z46mwfbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-z46mwfbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-303-z46mwfbq.web.app

**Comment by hanlunBCRegistries** [comment]
all fixed, please feel free to QA the work @nsmenon8890

**Comment by EPortman** [comment]
This is still in English, was this supposed to be fixed as well?

image

**Comment by hanlunBCRegistries** [comment]
> This is still in English, was this supposed to be fixed as well?
> 
> image

It is a placeholder in app.vue, cannot switch with watch function in current implementation
image

**Review by EPortman — APPROVED** [review]
Approved, although there is still English on the page.

**Comment by nsmenon8890** [comment]
Tested and I was able to change the language to French.

**Comment by nsmenon8890** [comment]
"Enter a nano id " is not changed to French.

**Comment by nsmenon8890** [comment]
Also if I click on any links in the page, the new page is displayed in English.

**Pull request merged**
