### PR TITLE
Web unit tests

### PR DESCRIPTION
**Pull request by deetz99**
- unit tests
- unit test mock data/helpers
- add vitest coverage
- rename pinia store ids with 'bar' prefix
- update loading state, use spinner/overlay when loading page data, use nuxt ui button spinner when submitting forms
- wrap account dropdown and choose account options in ClientOnly to prevent hydration errors

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-69-6vheh4a3.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-69-6vheh4a3.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-69-6vheh4a3.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
