### PR TITLE
394 fix linting

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
# Fix Linting and Formatting Issues

## Description
This pull request resolves multiple linter and formatting issues across the repository to enhance code consistency and ensure compliance with our code quality standards. Key changes include:

- **Linting Corrections**: Resolved various linting errors for better code readability and maintainability.
- **Configuration Updates**: Adjusted `pyproject.toml` and related config files for improved compatibility with linting tools.
- **Code Cleanup**: Addressed whitespace, line length, and unused imports flagged by the linter.

### CODE REVIEW

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries - can you please provide an update on this tix?

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson This ticket is complete and waiting for code review

**Comment by EPortman** [comment]
@hanlunBCRegistries do you mind taking off the DRAFT flag so I can review it?

**Comment by hanlunBCRegistries** [comment]
@EPortman Just updated, thank you for pointing it out

**Review by EPortman — APPROVED** [review]
Looks great!

**Pull request merged**
