### PR TITLE
Update Header and Remove References to SBC Connect

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
issue: #290 
* update Branding to "BC Registries and Digital Services" in Locale Files

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-291-pkh7c3g1.web.app

**Comment by EPortman** [comment]
This PR is the exact same as https://github.com/bcgov/business-ar/pull/280/files

**Comment by magszymanski** [comment]
"Service BC Connect" still appears on the Existing Account Found screen:

**Pull request closed without merging**
