### PR TITLE
Mags-agm-3rd-option-chanhe-aug1

### PR DESCRIPTION
**Pull request by magszymanski**
updates to 3rd agm option per ticket #285

### CODE REVIEW

**Comment by magszymanski** [comment]
Anyone available to do the PR pretty please? Looking to have this deployed to prod asap (after reviewing the temp URL, of course). Plus, looks like this one didn't make it into dev:https://github.com/bcgov/business-ar/pull/276 - can we lump that one in?

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-296-m4t4fzpj.web.app

**Comment by magszymanski** [comment]
This is what I get when I click on that URL:  

image

**Comment by hanlunBCRegistries** [comment]
> This is what I get when I click on that URL:
> 
> image

It looks like this when input nano id: 
image

**Comment by magszymanski** [comment]
Great! What is the next step to get this and https://github.com/bcgov/business-ar/pull/276 deployed? Goal is to get it to prod before Monday, when the next set of reminders go out.

**Comment by Maribeth-Wilson** [comment]
I will reach out to Thor and see when he can take a look at this

**Review by EPortman — APPROVED** [review]
Syntax looks good to me, I cannot really speak on the French though.

Update version number?

**Pull request merged**
