### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by deetz99**
checkpoint for current work

- login page
- choose existing account page
- create account page - functionality not working yet
- file ar page - functionality not working yet

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-47-kaw8csjv.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-ar-dev--pr-47-kaw8csjv.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
